### PR TITLE
example

### PR DESCRIPTION
**Pull request by alan-forbes-cp**

### CODE REVIEW

**Comment by alan-forbes-cp** [comment]
nope

**Comment by alan-forbes-cp** [comment]
easter-road-seating-plan
Capture

**Comment by alan-forbes-cp** [comment]
arse

**Comment by alan-forbes-cp** [comment]
rubbish

**Comment by scottstraughan** [comment]
/verify 584e585dda771507bd830fcd8f97c6c177f00963 @alan-forbes-cp **Codeplay Internal Testing: Started**

**Comment by scottstraughan** [comment]
/verify 584e585dda771507bd830fcd8f97c6c177f00963 @alan-forbes-cp **Codeplay Internal Testing: Completed: {'FAIL'}**

**Exit Code**: -2
**Result**:

Hello World!

**Comment by scottstraughan** [comment]
/verify 584e585dda771507bd830fcd8f97c6c177f00963 @alan-forbes-cp **Codeplay Internal Testing: Completed: FAIL**

**Exit Code**: -2
**Result**:

Hello World!

**Comment by scottstraughan** [comment]
/verify 584e585dda771507bd830fcd8f97c6c177f00963 @alan-forbes-cp **Codeplay Internal Testing: Started**

**Comment by scottstraughan** [comment]
/verify 584e585dda771507bd830fcd8f97c6c177f00963 @alan-forbes-cp **Codeplay Internal Testing: Completed: PASS**

**Exit Code**: 0
**Result**:

.
..
.git
.github
README.md

**Comment by scottstraughan** [comment]
/verify 584e585dda771507bd830fcd8f97c6c177f00963 @alan-forbes-cp **Codeplay Internal Testing: Started**

**Comment by scottstraughan** [comment]
/verify 584e585dda771507bd830fcd8f97c6c177f00963 @alan-forbes-cp **Codeplay Internal Testing: Completed: PASS**

**Exit Code**: 0
**Result**:

.
..
.git
.github
README.md

**Pull request closed without merging**
